PROJECT = device_service
DEPS = emqttc msgpack lager jsx ezmq poolboy recon observer_cli uuid ecache exometer
dep_emqttc = git https://github.com/macpie/emqttc.git master
dep_msgpack = git https://github.com/msgpack/msgpack-erlang.git 0.5.0
dep_lager = git https://github.com/erlang-lager/lager.git 3.5.2
dep_ezmq = git https://github.com/zeromq/ezmq.git
dep_jsx = git https://github.com/talentdeficit/jsx.git
dep_poolboy = git https://github.com/devinus/poolboy.git
dep_recon = git https://github.com/ferd/recon.git
dep_exometer = git https://github.com/Feuerlabs/exometer.git
dep_observer_cli = git https://github.com/zhongwencool/observer_cli.git
dep_uuid = git https://github.com/avtobiff/erlang-uuid.git
dep_ecache = git https://github.com/mattsta/ecache.git
include erlang.mk
