CREATE CONSTRAINT ON (org:Org) ASSERT org.orgid IS UNIQUE;
CREATE CONSTRAINT ON (site:Site) ASSERT site.siteid IS UNIQUE;
CREATE CONSTRAINT ON (node:Node) ASSERT node.nodeid IS UNIQUE;
CREATE CONSTRAINT ON (f:Fixture) ASSERT f.fixtureid IS UNIQUE;
CREATE CONSTRAINT ON (c:Config) ASSERT c.configid IS UNIQUE;
CREATE CONSTRAINT ON (g:Group) ASSERT g.groupid is UNIQUE;
CREATE CONSTRAINT ON (fw:Firmware) ASSERT fw.firmwareid is UNIQUE;
CREATE CONSTRAINT ON (sch:Schedule) ASSERT sch.scheduleid is UNIQUE;
CREATE CONSTRAINT ON (u:User) ASSERT u.userid IS UNIQUE;
CREATE CONSTRAINT ON (u:User) ASSERT u.email IS UNIQUE;
CREATE CONSTRAINT ON (r:Role) ASSERT r.rolename IS UNIQUE;
CREATE CONSTRAINT ON (pd:PDProfile) ASSERT pd.pdprofileid IS UNIQUE;
CREATE CONSTRAINT ON (dh:DHProfile) ASSERT dh.dhprofileid IS UNIQUE;
CREATE CONSTRAINT ON (etdh:ETDHProfile) ASSERT etdh.etdhprofileid IS UNIQUE;
CREATE INDEX ON :Alert(nodeid);
CREATE INDEX ON :Alert(name);
CREATE INDEX ON :Alert(type);
CREATE CONSTRAINT ON (a:Alert) ASSERT a.alertid IS UNIQUE;
CREATE CONSTRAINT ON (sm:SiteModel) ASSERT sm.smid IS UNIQUE;
CREATE CONSTRAINT ON (nm:NodeModel) ASSERT nm.nmid IS UNIQUE;
CREATE CONSTRAINT ON (cm:ConfigModel) ASSERT cm.cmid IS UNIQUE;
CREATE CONSTRAINT ON (um:UserModel) ASSERT um.umid IS UNIQUE;
CREATE CONSTRAINT ON (om:OrgModel) ASSERT om.omid IS UNIQUE;
CREATE CONSTRAINT ON (olm:OverlayModel) ASSERT olm.olmid IS UNIQUE;
CREATE CONSTRAINT ON (fwm:FirmwareModel) ASSERT fwm.fwmid IS UNIQUE;
CREATE CONSTRAINT ON (am:AuditModel) ASSERT am.amid IS UNIQUE;
CREATE CONSTRAINT ON (fm:FixtureModel) ASSERT fm.fmid IS UNIQUE;
CREATE CONSTRAINT ON (nfm:NotificationModel) ASSERT nfm.nfmid IS UNIQUE;
CREATE CONSTRAINT ON (n:Notification) ASSERT n.notificationid IS UNIQUE;
CREATE CONSTRAINT ON (pz:ParkingZoneModel) ASSERT pz.parkingzoneid IS UNIQUE;
CREATE CONSTRAINT ON (tom:TrafficObjectModel) ASSERT tom.tomid is UNIQUE;
CREATE CONSTRAINT ON (alm:AlertModel) ASSERT alm.almid IS UNIQUE;
CREATE CONSTRAINT ON (gm:GroupModel) ASSERT gm.gmid IS UNIQUE;
CREATE CONSTRAINT ON (scm:ScheduleModel) ASSERT scm.scmid is UNIQUE;
CREATE CONSTRAINT ON (pm:PartnerModel) ASSERT pm.pmid is UNIQUE;
CREATE CONSTRAINT ON (rm:ReportModel) ASSERT rm.rmid is UNIQUE;
CREATE CONSTRAINT ON (lcm:LicenseModel) ASSERT lcm.lcmid is UNIQUE;

CREATE CONSTRAINT ON (psm:ParkingSpotModel) ASSERT psm.psmid is UNIQUE;
CREATE CONSTRAINT ON (ppm:ParkingPolicyModel) ASSERT ppm.ppmid is UNIQUE;
CREATE CONSTRAINT ON (pcm:PolicyCategoryModel) ASSERT pcm.pcmid is UNIQUE;
CREATE CONSTRAINT ON (pgm:ParkingGroupModel) ASSERT pgm.pgmid is UNIQUE;
CREATE CONSTRAINT ON (srm:SummaryReportModel) ASSERT srm.srmid is UNIQUE;

MERGE (psm:ParkingSpotModel:Model {psmid: "psmid", name: "ParkingSpotModel"}) ON CREATE SET psm.created=timestamp()
MERGE (ppm:ParkingPolicyModel:Model {ppmid: "ppmid", name: "ParkingPolicyModel"}) ON CREATE SET ppm.created=timestamp()
MERGE (pcm:PolicyCategoryModel:Model {pcmid: "pcmid", name: "PolicyCategoryModel"}) ON CREATE SET pcm.created=timestamp()
MERGE (pgm:ParkingGroupModel:Model {pgmid: "pgmid", name: "ParkingGroupModel"}) ON CREATE SET pgm.created=timestamp()
MERGE (srm:SummaryReportModel:Model {srmid: "srmid", name: "SummaryReportModel"}) ON CREATE SET srm.created=timestamp()


MERGE (om:OrgModel:Model {omid: "omid", name: "OrgModel"})
    ON CREATE SET om.created=timestamp()
MERGE (sm:SiteModel:Model {smid: "smid", name: "SiteModel"})
    ON CREATE SET sm.created=timestamp()
MERGE (nm:NodeModel:Model {nmid: "nmid", name: "NodeModel"})
    ON CREATE SET nm.created=timestamp()
MERGE (cm:ConfigModel:Model {cmid: "cmid", name: "ConfigModel"})
    ON CREATE SET cm.created=timestamp()
MERGE (um:UserModel:Model {umid: "umid", name: "UserModel"})
    ON CREATE SET um.created=timestamp()
MERGE(olm:OverlayModel:Model {olmid: "olmid", name: "OverlayModel"})
    ON CREATE SET olm.created=timestamp()
MERGE(fwm:FirmwareModel:Model {fwmid: "fwmid", name: "FirmwareModel"})
    ON CREATE SET fwm.created=timestamp()
MERGE(am:AuditModel:Model {amid: "amid", name: "AuditModel"})
    ON CREATE SET am.created=timestamp()
MERGE(fm:FixtureModel:Model {fmid: "fmid", name: "FixtureModel"})
    ON CREATE SET fm.created=timestamp()
MERGE(nfm:NotificationModel:Model {nfmid: "nfmid", name: "NotificationModel"})
    ON CREATE SET nfm.created=timestamp()
MERGE(pz:ParkingZoneModel:Model {parkingzoneid: "parkingzoneid", name: "ParkingZoneModel"})
    ON CREATE SET pz.created=timestamp()
MERGE(tom:TrafficObjectModel:Model {tomid: "tomid", name: "TrafficObjectModel"})
    ON CREATE SET tom.created=timestamp()
MERGE(alm:AlertModel:Model {almid: "almid", name: "AlertModel"})
    ON CREATE SET alm.created=timestamp()
MERGE(gm:GroupModel:Model {gmid: "gmid", name: "GroupModel"})
    ON CREATE SET gm.created=timestamp()
MERGE(scm:ScheduleModel:Model {scmid: "scmid", name: "ScheduleModel"})
    ON CREATE SET scm.created=timestamp()
MERGE(pm:PartnerModel:Model {pmid: "pmid", name: "PartnerModel", created: timestamp()})
MERGE(rm:ReportModel:Model {rmid: "rmid", name: "ReportModel", created: timestamp()})
MERGE(lcm:LicenseModel:Model {lcmid: "lcmid", name: "LicenseModel", created: timestamp()})

MERGE (ro_sa:Role {rolename: "super_admin"})
    ON CREATE SET ro_sa.created=timestamp()
MERGE (ro_ad:Role {rolename: "customer_admin"})
    ON CREATE SET ro_ad.created=timestamp()
MERGE (ro_op:Role {rolename: "operator"})
    ON CREATE SET ro_op.created=timestamp()

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(olm)
CREATE UNIQUE (ro_ad)-[:CAN_UPDATE]->(olm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(olm)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(olm)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(fwm)
CREATE UNIQUE (ro_ad)-[:CAN_UPDATE]->(fwm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(fwm)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(fwm)

CREATE UNIQUE (ro_ad)-[:CAN_READ]->(am)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (ro_ad)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(fm)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(fm)

CREATE UNIQUE (ro_op)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (ro_op)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (ro_op)-[:CAN_MOVE]->(nm)
CREATE UNIQUE (ro_op)-[:CAN_READ]->(nm)
CREATE UNIQUE (ro_op)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (ro_op)-[:CAN_DEACTIVATE]->(nm)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_MOVE]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_UPGRADE_FIRMWARE]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (ro_ad)-[:CAN_ASSIGN_TO_SITES]->(nm)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(cm)
CREATE UNIQUE (ro_ad)-[:CAN_UPDATE]->(cm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(cm)
CREATE UNIQUE (ro_ad)-[:CAN_DEACTIVATE]->(cm)
CREATE UNIQUE (ro_ad)-[:CAN_APPLY]->(cm)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (ro_ad)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(sm)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(sm)
CREATE UNIQUE (ro_ad)-[:CAN_GEN_REPORT]->(sm)
CREATE UNIQUE (ro_ad)-[:CAN_SEE_ALL_ACTIVITY_LOG]->(sm)
CREATE UNIQUE (ro_ad)-[:CAN_SEE_OWN_ACTIVITY_LOG]->(sm)

CREATE UNIQUE (ro_sa)-[:CAN_CREATE]->(om)
CREATE UNIQUE (ro_sa)-[:CAN_READ]->(om)
CREATE UNIQUE (ro_sa)-[:CAN_DELETE]->(om)
CREATE UNIQUE (ro_sa)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (ro_sa)-[:CAN_ADD_SITE]->(om)

CREATE UNIQUE (ro_sa)-[:CAN_CREATE_USER]->(um)
CREATE UNIQUE (ro_sa)-[:CAN_DELETE_USER]->(um)
CREATE UNIQUE (ro_sa)-[:CAN_CHANGE_USER]->(um)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(om)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(om)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(om)
CREATE UNIQUE (ro_ad)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (ro_ad)-[:CAN_ADD_SITE]->(om)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(nfm)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (ro_ad)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (ro_ad)-[:CAN_ADD_SITE]->(nfm)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(alm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(alm)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(alm)
CREATE UNIQUE (ro_ad)-[:CAN_UPDATE]->(alm)
CREATE UNIQUE (ro_ad)-[:CAN_ADD_SITE]->(alm)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (ro_ad)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(scm)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (ro_ad)-[:CAN_APPLY]->(scm)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (ro_ad)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (ro_ad)-[:CAN_READ]->(gm)
CREATE UNIQUE (ro_ad)-[:CAN_DELETE]->(gm)

CREATE UNIQUE (ro_ad)-[:CAN_CREATE_ORG_USER]->(um)
CREATE UNIQUE (ro_ad)-[:CAN_SUSPEND_ORG_USER]->(um)
CREATE UNIQUE (ro_ad)-[:CAN_CHANGE_ORG_USER]->(um)
CREATE UNIQUE (ro_ad)-[:CAN_READ_ORG_USER]->(um)


CREATE (sensity_admin:Role:Admin {rolename: "sensity_admin", created: timestamp()})
CREATE (sensity_read_only:Role:Admin {rolename: "sensity_read_only", created: timestamp()})
CREATE (sensity_user:Role:Admin {rolename: "sensity_user", created: timestamp()})

CREATE (partner_admin:Role {rolename: "partner_admin", created: timestamp()})
CREATE (partner_deployment_user:Role {rolename: "partner_deployment_user", created: timestamp()})
CREATE (partner_lighting_user:Role {rolename: "partner_lighting_user", created: timestamp()})
CREATE (partner_sensor_user:Role {rolename: "partner_sensor_user", created: timestamp()})
CREATE (partner_networking_user:Role {rolename: "partner_networking_user", created: timestamp()})
CREATE (partner_read_only:Role {rolename: "partner_read_only", created: timestamp()})
CREATE (partner_api:Role {rolename: "partner_api", created: timestamp()})

CREATE (end_user_admin:Role {rolename: "end_user_admin", created: timestamp()})
CREATE (end_user_lighting_user:Role {rolename: "end_user_lighting_user", created: timestamp()})
CREATE (end_user_sensor_user:Role {rolename: "end_user_sensor_user", created: timestamp()})
CREATE (end_user_networking_user:Role {rolename: "end_user_networking_user", created: timestamp()})
CREATE (end_user_read_only:Role {rolename: "end_user_read_only", created: timestamp()})
CREATE (end_user_api:Role {rolename: "end_user_api", created: timestamp()})


MERGE (parking_owner_admin:Role {rolename: "parking_owner_admin"}) ON CREATE SET parking_owner_admin.created=timestamp()
MERGE (parking_manager:Role {rolename: "parking_manager"}) ON CREATE SET parking_manager.created=timestamp()
MERGE (policy_authority:Role {rolename: "policy_authority"}) ON CREATE SET policy_authority.created=timestamp()

CREATE (installer:Role {rolename: "installer", created: timestamp()})

CREATE (sensity:Org:Active {orgid: "efe5bdb3-baac-5d8e-6cae57771c10", name: "Sensity Systems", street1: "1237 East Arques Ave", street2: "", city: "Sunnyvale", state: "CA", postal_code: "94085", country: "USA", created: timestamp()})
CREATE (sensity_admin_user:User:Active {userid: "114ad560-a046-11e5-a57f-ef24ae600576", email: "sensity_admin@sensity.com", name: "Sensity Admin", phone: "+1 234 555 666", roles: "sensity_admin", created: timestamp(), updated:timestamp()})

CREATE UNIQUE (sensity_admin_user)-[:IS]->(sensity_admin)
CREATE UNIQUE (sensity_admin)-[:HAS]->(sensity_admin_user)
CREATE UNIQUE (sensity_admin_user)-[:IS_USER_OF]->(sensity)
CREATE UNIQUE (sensity)-[:HAS_USER]->(sensity_admin_user)

CREATE (sensity_user_user:User:Active {userid: "507ef3cc-cd2d-46d8-ae6d-7ccf430c1110", email: "sensity_user@sensity.com", name: "Sensity User", roles: "sensity_user", created: timestamp(), updated:timestamp()})

CREATE UNIQUE (sensity_user_user)-[:IS]->(sensity_user)
CREATE UNIQUE (sensity_user)-[:HAS]->(sensity_user_user)
CREATE UNIQUE (sensity_user_user)-[:IS_USER_OF]->(sensity)
CREATE UNIQUE (sensity)-[:HAS_USER]->(sensity_user_user)

CREATE (sensity_read_only_user:User:Active {userid: "47e3e2f2-b93b-4557-b668-271d43d028ac", email: "sensity_read_only@sensity.com", name: "Sensity Read Only", roles: "sensity_read_only", created: timestamp(), updated:timestamp()})

CREATE UNIQUE (sensity_read_only_user)-[:IS]->(sensity_read_only)
CREATE UNIQUE (sensity_read_only)-[:HAS]->(sensity_read_only_user)
CREATE UNIQUE (sensity_read_only_user)-[:IS_USER_OF]->(sensity)
CREATE UNIQUE (sensity)-[:HAS_USER]->(sensity_read_only_user)

CREATE (sch:Schedule {scheduleid: "default", name: "Default Schedule"})
CREATE (ce:CalendarEvents {days: ["mon","tue","wed","thu","fri","sat","sun"], photocell_enabled: true, photocell_highLevel: 100, photocell_lowLevel: 0})
CREATE UNIQUE (ce)-[:BELONGS_TO]->(sch)
CREATE UNIQUE (sch)-[:HAS]->(ce)
CREATE (a:Action {id: 2, time: "00:00:00", level: 100})
CREATE UNIQUE (ce)-[:HAS]->(a)
CREATE UNIQUE (a)-[:BELONGS_TO]->(ce)
CREATE (nnw:NoNetwork {photocell_enabled: true, photocell_highLevel: 100, photocell_lowLevel: 0})
CREATE (sch)-[:HAS]->(nnw)-[:BELONGS_TO]->(sch)

CREATE (c:Config {configid: "default"})

CREATE UNIQUE (sensity_admin)-[:CAN_CREATE]->(pm)
CREATE UNIQUE (sensity_admin)-[:CAN_DELETE]->(pm)
CREATE UNIQUE (sensity_admin)-[:CAN_UPDATE]->(pm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(pm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(pm)
CREATE UNIQUE (sensity_user)-[:CAN_SUSPEND]->(pm)
CREATE UNIQUE (partner_admin)-[:CAN_SUSPEND]->(pm)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(pm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(pm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(pm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(pm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(pm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(pm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_READ]->(pm)
CREATE UNIQUE (partner_networking_user)-[:CAN_READ]->(pm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(pm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(pm)
CREATE UNIQUE (sensity_admin)-[:CAN_CREATE]->(om)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(om)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(om)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(om)
CREATE UNIQUE (sensity_admin)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (sensity_user)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (partner_admin)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (partner_lighting_user)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (end_user_admin)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (sensity_admin)-[:CAN_SUSPEND]->(om)
CREATE UNIQUE (sensity_user)-[:CAN_SUSPEND]->(om)
CREATE UNIQUE (partner_admin)-[:CAN_SUSPEND]->(om)
CREATE UNIQUE (partner_api)-[:CAN_SUSPEND]->(om)
CREATE UNIQUE (sensity_admin)-[:CAN_DELETE]->(om)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(om)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(om)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(om)
CREATE UNIQUE (partner_api)-[:CAN_DELETE]->(om)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(om)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(om)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(om)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(om)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(om)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(om)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(om)
CREATE UNIQUE (partner_sensor_user)-[:CAN_READ]->(om)
CREATE UNIQUE (partner_networking_user)-[:CAN_READ]->(om)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(om)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(om)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(om)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(om)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(om)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (sensity_user)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (partner_admin)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (partner_api)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (end_user_admin)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (end_user_api)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (sensity_user)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (partner_admin)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (partner_api)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (end_user_admin)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (end_user_api)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(sm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(sm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(sm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(sm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(sm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(sm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_READ]->(sm)
CREATE UNIQUE (partner_networking_user)-[:CAN_READ]->(sm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(sm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(sm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(sm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(sm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_READ]->(sm)
CREATE UNIQUE (end_user_networking_user)-[:CAN_READ]->(sm)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(sm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(sm)
CREATE UNIQUE (installer)-[:CAN_READ]->(sm)
CREATE UNIQUE (sensity_admin)-[:CAN_CREATE_ORG_USER]->(um)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE_ORG_USER]->(um)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE_ORG_USER]->(um)
CREATE UNIQUE (partner_api)-[:CAN_CREATE_ORG_USER]->(um)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE_ORG_USER]->(um)
CREATE UNIQUE (sensity_admin)-[:CAN_CHANGE_ORG_USER]->(um)
CREATE UNIQUE (sensity_user)-[:CAN_CHANGE_ORG_USER]->(um)
CREATE UNIQUE (partner_admin)-[:CAN_CHANGE_ORG_USER]->(um)
CREATE UNIQUE (partner_api)-[:CAN_CHANGE_ORG_USER]->(um)
CREATE UNIQUE (end_user_admin)-[:CAN_CHANGE_ORG_USER]->(um)
CREATE UNIQUE (sensity_admin)-[:CAN_SUSPEND_ORG_USER]->(um)
CREATE UNIQUE (sensity_user)-[:CAN_SUSPEND_ORG_USER]->(um)
CREATE UNIQUE (partner_admin)-[:CAN_SUSPEND_ORG_USER]->(um)
CREATE UNIQUE (partner_api)-[:CAN_SUSPEND_ORG_USER]->(um)
CREATE UNIQUE (end_user_admin)-[:CAN_SUSPEND_ORG_USER]->(um)
CREATE UNIQUE (sensity_admin)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (sensity_user)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (partner_admin)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (partner_sensor_user)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (partner_networking_user)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (partner_read_only)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (partner_api)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (end_user_admin)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (end_user_networking_user)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (end_user_api)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (sensity_admin)-[:CAN_GENERATE_API_KEY]->(um)
CREATE UNIQUE (partner_admin)-[:CAN_GENERATE_API_KEY]->(um)
CREATE UNIQUE (end_user_admin)-[:CAN_GENERATE_API_KEY]->(um)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (partner_api)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (partner_api)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(gm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(gm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(gm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(gm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(gm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_READ]->(gm)
CREATE UNIQUE (partner_networking_user)-[:CAN_READ]->(gm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(gm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(gm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(gm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(gm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_READ]->(gm)
CREATE UNIQUE (end_user_networking_user)-[:CAN_READ]->(gm)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(gm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(gm)
CREATE UNIQUE (installer)-[:CAN_READ]->(gm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(lcm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(lcm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(lcm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(lcm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(lcm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(lcm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(lcm)
CREATE UNIQUE (sensity_user)-[:CAN_READ_USAGE]->(lcm)
CREATE UNIQUE (partner_admin)-[:CAN_READ_USAGE]->(lcm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ_USAGE]->(lcm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(lcm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(lcm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(lcm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (partner_api)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (partner_api)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(scm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(scm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(scm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(scm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(scm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_READ]->(scm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(scm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(scm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(scm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(scm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_READ]->(scm)
CREATE UNIQUE (end_user_networking_user)-[:CAN_READ]->(scm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(scm)
CREATE UNIQUE (sensity_user)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (partner_admin)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (partner_api)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (end_user_admin)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (end_user_api)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (sensity_user)-[:CAN_ASSIGN_TO_LS_GROUP]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_ASSIGN_TO_LS_GROUP]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_ASSIGN_TO_LS_GROUP]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_ASSIGN_TO_LS_GROUP]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_ASSIGN_TO_LS_GROUP]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_ASSIGN_TO_LS_GROUP]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_ASSIGN_TO_LS_GROUP]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_ASSIGN_LM_DETECTION_TO_GROUP]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_ASSIGN_LM_DETECTION_TO_GROUP]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_ASSIGN_LM_DETECTION_TO_GROUP]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_ASSIGN_LM_DETECTION_TO_GROUP]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_ASSIGN_LM_DETECTION_TO_GROUP]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_ASSIGN_LM_DETECTION_TO_GROUP]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_ASSIGN_LM_DETECTION_TO_GROUP]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (installer)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(nm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(nm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(nm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_READ]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(nm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(nm)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(nm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_READ]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(nm)
CREATE UNIQUE (installer)-[:CAN_READ]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (installer)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (installer)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (installer)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (installer)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (installer)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (installer)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (installer)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_UPGRADE_FIRMWARE]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPGRADE_FIRMWARE]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_UPGRADE_FIRMWARE]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPGRADE_FIRMWARE]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPGRADE_FIRMWARE]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_UPGRADE_FIRMWARE]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (installer)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (sensity_admin)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (sensity_read_only)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (partner_read_only)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (end_user_read_only)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (sensity_admin)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (sensity_read_only)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (partner_read_only)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (end_user_read_only)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (installer)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (sensity_admin)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (sensity_read_only)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (sensity_user)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (partner_read_only)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (partner_api)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (end_user_admin)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (end_user_read_only)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (end_user_api)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (installer)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(cm)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(cm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(cm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(cm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(cm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(cm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(cm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(cm)
CREATE UNIQUE (partner_api)-[:CAN_UPDATE]->(cm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(cm)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(cm)
CREATE UNIQUE (sensity_user)-[:CAN_DEACTIVATE]->(cm)
CREATE UNIQUE (partner_admin)-[:CAN_DEACTIVATE]->(cm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DEACTIVATE]->(cm)
CREATE UNIQUE (partner_api)-[:CAN_DEACTIVATE]->(cm)
CREATE UNIQUE (end_user_admin)-[:CAN_DEACTIVATE]->(cm)
CREATE UNIQUE (end_user_api)-[:CAN_DEACTIVATE]->(cm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(cm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(cm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(cm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(cm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(cm)
CREATE UNIQUE (partner_sensor_user)-[:CAN_READ]->(cm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(cm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(cm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(cm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(cm)
CREATE UNIQUE (end_user_sensor_user)-[:CAN_READ]->(cm)
CREATE UNIQUE (end_user_networking_user)-[:CAN_READ]->(cm)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(cm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(cm)
CREATE UNIQUE (sensity_user)-[:CAN_APPLY]->(cm)
CREATE UNIQUE (partner_admin)-[:CAN_APPLY]->(cm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_APPLY]->(cm)
CREATE UNIQUE (partner_api)-[:CAN_APPLY]->(cm)
CREATE UNIQUE (end_user_admin)-[:CAN_APPLY]->(cm)
CREATE UNIQUE (end_user_api)-[:CAN_APPLY]->(cm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(fm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(fm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(fm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(fm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(fm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(fm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(fm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(fm)
CREATE UNIQUE (installer)-[:CAN_READ]->(fm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (installer)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (partner_api)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (installer)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (partner_lighting_user)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (partner_api)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (installer)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(am)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(am)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(am)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(am)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(am)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(am)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(am)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(am)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(am)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(am)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(am)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(am)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(am)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(am)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(am)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(am)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(am)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(am)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(am)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(am)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(am)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(am)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(am)
CREATE UNIQUE (partner_lighting_user)-[:CAN_READ]->(am)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(am)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(am)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(am)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(am)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(am)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(am)
CREATE UNIQUE (installer)-[:CAN_READ]->(am)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(fwm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(fwm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(fwm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(fwm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(fwm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(fwm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(fwm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(fwm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(fwm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(fwm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(fwm)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(fwm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(fwm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(fwm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(fwm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(fwm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(fwm)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(fwm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(fwm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(fwm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(fwm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(fwm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(fwm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(fwm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(fwm)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(fwm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(fwm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (partner_api)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (partner_api)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(nfm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(nfm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(nfm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(nfm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(nfm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(nfm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(nfm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(nfm)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(nfm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(nfm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(pz)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(pz)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(pz)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(pz)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(pz)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(pz)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(pz)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(pz)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(pz)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(pz)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(pz)
CREATE UNIQUE (partner_api)-[:CAN_UPDATE]->(pz)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(pz)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(pz)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(pz)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(pz)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(pz)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(pz)
CREATE UNIQUE (partner_api)-[:CAN_DELETE]->(pz)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(pz)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(pz)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(pz)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(pz)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(pz)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(pz)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(pz)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(pz)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(pz)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(pz)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(pz)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(pz)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(tom)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(tom)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(tom)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(tom)
CREATE UNIQUE (partner_api)-[:CAN_CREATE]->(tom)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(tom)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(tom)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(tom)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(tom)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(tom)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(tom)
CREATE UNIQUE (partner_api)-[:CAN_UPDATE]->(tom)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(tom)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(tom)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(tom)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(tom)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(tom)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(tom)
CREATE UNIQUE (partner_api)-[:CAN_DELETE]->(tom)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(tom)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(tom)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(tom)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(tom)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(tom)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(tom)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(tom)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(tom)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(tom)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(tom)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(tom)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(tom)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(alm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(alm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(alm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(alm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(alm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(alm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(alm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(alm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(alm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(alm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(alm)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(alm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(alm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(alm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(alm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(alm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(alm)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(alm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(alm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(alm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(alm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(alm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(alm)
CREATE UNIQUE (partner_api)-[:CAN_READ]->(alm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(alm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(alm)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(alm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(alm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(olm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(olm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_CREATE]->(olm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(olm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_CREATE]->(olm)
CREATE UNIQUE (end_user_api)-[:CAN_CREATE]->(olm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(olm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(olm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_UPDATE]->(olm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(olm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_UPDATE]->(olm)
CREATE UNIQUE (end_user_api)-[:CAN_UPDATE]->(olm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(olm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(olm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_DELETE]->(olm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(olm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_DELETE]->(olm)
CREATE UNIQUE (end_user_api)-[:CAN_DELETE]->(olm)
CREATE UNIQUE (sensity_read_only)-[:CAN_READ]->(olm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(olm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(olm)
CREATE UNIQUE (partner_deployment_user)-[:CAN_READ]->(olm)
CREATE UNIQUE (partner_read_only)-[:CAN_READ]->(olm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(olm)
CREATE UNIQUE (end_user_lighting_user)-[:CAN_READ]->(olm)
CREATE UNIQUE (end_user_read_only)-[:CAN_READ]->(olm)
CREATE UNIQUE (end_user_api)-[:CAN_READ]->(olm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(end_user_lighting_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(end_user_sensor_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(end_user_networking_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(end_user_read_only)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(end_user_api)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(installer)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(parking_owner_admin)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(end_user_lighting_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(end_user_sensor_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(end_user_networking_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(end_user_read_only)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(end_user_api)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(installer)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(parking_owner_admin)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(end_user_lighting_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(end_user_sensor_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(end_user_networking_user)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(end_user_read_only)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(end_user_api)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(installer)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(om)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(om)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(om)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(sm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE_ORG_USER]->(um)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE_ORG_USER]->(um)
CREATE UNIQUE (parking_owner_admin)-[:CAN_SUSPEND_ORG_USER]->(um)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (parking_owner_admin)-[:CAN_GENERATE_API_KEY]->(um)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(gm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(lcm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(lcm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ_USAGE]->(lcm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(lcm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(scm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(scm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(scm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(scm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_APPLY]->(scm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_ASSIGN_TO_LS_GROUP]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_ASSIGN_LM_DETECTION_TO_GROUP]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_MANAGE_LIGHTS]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DEACTIVATE]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_OPERATE]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_ASSIGN_TO_ORGS]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_ASSIGN_TO_SITES]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_ASSIGN_TO_GROUPS]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPGRADE_FIRMWARE]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_ASSIGN_FIXTURE]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_SEARCH]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_RETRIEVE_LOG_FILE]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_RETRIEVE_ALARM]->(nm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(cm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(cm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DEACTIVATE]->(cm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(cm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_APPLY]->(cm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(fm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(fm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(fm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(fm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(am)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(am)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(am)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(am)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(fwm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(fwm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(fwm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(fwm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(nfm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(nfm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(nfm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(nfm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(pz)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(pz)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(pz)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(pz)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(tom)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(tom)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(tom)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(tom)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(alm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(alm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(alm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(alm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(olm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(olm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(olm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(olm)

CREATE UNIQUE (sensity_user)-[:CAN_READ]->(psm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(psm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(psm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(psm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(ppm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(ppm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(ppm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(ppm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(pcm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(pcm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(pcm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(pcm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(pgm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(pgm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(pgm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(pgm)
CREATE UNIQUE (sensity_user)-[:CAN_READ]->(srm)
CREATE UNIQUE (sensity_user)-[:CAN_CREATE]->(srm)
CREATE UNIQUE (sensity_user)-[:CAN_UPDATE]->(srm)
CREATE UNIQUE (sensity_user)-[:CAN_DELETE]->(srm)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(psm)
CREATE UNIQUE (sensity_admin)-[:CAN_CREATE]->(psm)
CREATE UNIQUE (sensity_admin)-[:CAN_UPDATE]->(psm)
CREATE UNIQUE (sensity_admin)-[:CAN_DELETE]->(psm)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(ppm)
CREATE UNIQUE (sensity_admin)-[:CAN_CREATE]->(ppm)
CREATE UNIQUE (sensity_admin)-[:CAN_UPDATE]->(ppm)
CREATE UNIQUE (sensity_admin)-[:CAN_DELETE]->(ppm)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(pcm)
CREATE UNIQUE (sensity_admin)-[:CAN_CREATE]->(pcm)
CREATE UNIQUE (sensity_admin)-[:CAN_UPDATE]->(pcm)
CREATE UNIQUE (sensity_admin)-[:CAN_DELETE]->(pcm)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(pgm)
CREATE UNIQUE (sensity_admin)-[:CAN_CREATE]->(pgm)
CREATE UNIQUE (sensity_admin)-[:CAN_UPDATE]->(pgm)
CREATE UNIQUE (sensity_admin)-[:CAN_DELETE]->(pgm)
CREATE UNIQUE (sensity_admin)-[:CAN_READ]->(srm)
CREATE UNIQUE (sensity_admin)-[:CAN_CREATE]->(srm)
CREATE UNIQUE (sensity_admin)-[:CAN_UPDATE]->(srm)
CREATE UNIQUE (sensity_admin)-[:CAN_DELETE]->(srm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(psm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(psm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(psm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(psm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(ppm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(ppm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(ppm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(ppm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(pcm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(pcm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(pcm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(pcm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(pgm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(pgm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(pgm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(pgm)
CREATE UNIQUE (end_user_admin)-[:CAN_READ]->(srm)
CREATE UNIQUE (end_user_admin)-[:CAN_CREATE]->(srm)
CREATE UNIQUE (end_user_admin)-[:CAN_UPDATE]->(srm)
CREATE UNIQUE (end_user_admin)-[:CAN_DELETE]->(srm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(psm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(psm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(psm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(psm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(ppm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(ppm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(ppm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(ppm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(pcm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(pcm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(pcm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(pcm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(pgm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(pgm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(pgm)
CREATE UNIQUE (partner_admin)-[:CAN_DELETE]->(pgm)
CREATE UNIQUE (partner_admin)-[:CAN_READ]->(srm)
CREATE UNIQUE (partner_admin)-[:CAN_CREATE]->(srm)
CREATE UNIQUE (partner_admin)-[:CAN_UPDATE]->(srm)

CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(psm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(psm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(psm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(psm)

CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(ppm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(ppm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(ppm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(ppm)

CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(pcm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(pcm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(pcm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(pcm)

CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(pgm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(pgm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(pgm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(pgm)


CREATE UNIQUE (parking_owner_admin)-[:CAN_READ]->(srm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_CREATE]->(srm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_UPDATE]->(srm)
CREATE UNIQUE (parking_owner_admin)-[:CAN_DELETE]->(srm)


CREATE UNIQUE (parking_manager)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (parking_manager)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (parking_manager)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (parking_manager)-[:CAN_READ]->(sm)
CREATE UNIQUE (parking_manager)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (parking_manager)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (parking_manager)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (parking_manager)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (parking_manager)-[:CAN_READ]->(gm)
CREATE UNIQUE (parking_manager)-[:CAN_READ]->(scm)
CREATE UNIQUE (parking_manager)-[:CAN_READ]->(nm)
CREATE UNIQUE (parking_manager)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (parking_manager)-[:CAN_READ]->(cm)

CREATE UNIQUE (parking_manager)-[:CAN_READ]->(psm)

CREATE UNIQUE (parking_manager)-[:CAN_READ]->(ppm)

CREATE UNIQUE (parking_manager)-[:CAN_READ]->(pcm)

CREATE UNIQUE (parking_manager)-[:CAN_READ]->(pgm)

CREATE UNIQUE (parking_manager)-[:CAN_READ]->(srm)


CREATE UNIQUE (policy_authority)-[:CAN_CREATE]->(sm)
CREATE UNIQUE (policy_authority)-[:CAN_CHANGE]->(sm)
CREATE UNIQUE (policy_authority)-[:CAN_SUSPEND]->(sm)
CREATE UNIQUE (policy_authority)-[:CAN_READ]->(sm)
CREATE UNIQUE (policy_authority)-[:CAN_READ_ORG_USER]->(um)
CREATE UNIQUE (policy_authority)-[:CAN_CREATE]->(gm)
CREATE UNIQUE (policy_authority)-[:CAN_UPDATE]->(gm)
CREATE UNIQUE (policy_authority)-[:CAN_DELETE]->(gm)
CREATE UNIQUE (policy_authority)-[:CAN_READ]->(gm)
CREATE UNIQUE (policy_authority)-[:CAN_READ]->(scm)
CREATE UNIQUE (policy_authority)-[:CAN_READ]->(nm)
CREATE UNIQUE (policy_authority)-[:CAN_CHANGE]->(nm)
CREATE UNIQUE (policy_authority)-[:CAN_READ]->(cm)

CREATE UNIQUE (policy_authority)-[:CAN_READ]->(psm)
CREATE UNIQUE (policy_authority)-[:CAN_CREATE]->(psm)
CREATE UNIQUE (policy_authority)-[:CAN_UPDATE]->(psm)
CREATE UNIQUE (policy_authority)-[:CAN_DELETE]->(psm)

CREATE UNIQUE (policy_authority)-[:CAN_READ]->(ppm)
CREATE UNIQUE (policy_authority)-[:CAN_CREATE]->(ppm)
CREATE UNIQUE (policy_authority)-[:CAN_UPDATE]->(ppm)
CREATE UNIQUE (policy_authority)-[:CAN_DELETE]->(ppm)

CREATE UNIQUE (policy_authority)-[:CAN_READ]->(pcm)
CREATE UNIQUE (policy_authority)-[:CAN_CREATE]->(pcm)
CREATE UNIQUE (policy_authority)-[:CAN_UPDATE]->(pcm)
CREATE UNIQUE (policy_authority)-[:CAN_DELETE]->(pcm)

CREATE UNIQUE (policy_authority)-[:CAN_READ]->(pgm)
CREATE UNIQUE (policy_authority)-[:CAN_CREATE]->(pgm)
CREATE UNIQUE (policy_authority)-[:CAN_UPDATE]->(pgm)
CREATE UNIQUE (policy_authority)-[:CAN_DELETE]->(pgm)


CREATE UNIQUE (policy_authority)-[:CAN_READ]->(srm)
CREATE UNIQUE (policy_authority)-[:CAN_CREATE]->(srm)
CREATE UNIQUE (policy_authority)-[:CAN_UPDATE]->(srm)
CREATE UNIQUE (policy_authority)-[:CAN_DELETE]->(srm)

;

// Add Uber Test
MATCH (ro_ad) WHERE ro_ad.rolename="customer_admin"
MERGE (o0:Org:Active {orgid: "uberorg", name: "Uber Org", street1: "1455 Market St.", street2: "Suite 200", city: "San Francisco", state: "CA", postal_code: "94107", country: "USA"})
    ON CREATE SET o0.created=timestamp()
MERGE (u0:User:Active {userid: "uberuser", name: "Uber User", email:"uberuser@sensity.com", phone: "+1 234 555 666"})
    ON CREATE SET u0 += { created:timestamp() , updated:timestamp() }
MERGE (s0_0:Site:Active {siteid: "ubersite", name: "Uber Site", street1: "1455 Market St.", street2: "Suite 200", city: "San Francisco", state: "CA", postal_code: "94107", country: "USA", latitude: "37.7756123", longitude: "-122.4192791"})
    ON CREATE SET s0_0.created=timestamp()
MERGE (slg0:Group:LightingGroup:SiteLightingGroup {groupid: "ubersitelightinggroup",
                                                   name: "Site Lighting Group",
                                                   nodeList: []})
MERGE (n0_0:Node:Active {nodeid: "ubernode", name: "Uber Node", building: "2", longitude: "-122.16358207", latitude: "37.42790534", level: 3, time_zone: "America/Los_Angeles", model: "unode-v4"})
    ON CREATE SET n0_0.created=timestamp()
MERGE (g0_0:Group:Active {groupid: "ubergroup", name: "Uber Group", nodeList: "ubernode", created:timestamp()})
MERGE (ov0_0:Overlay:Active {overlayid: "uberoverlay", buildingLevel: "1", imageBounds: "30x30", imageData: "foo", created: timestamp()})
MERGE (f0_0:Fixture:Active {fixtureid: "uberfixture", name: "Uber Fixture", created: timestamp()})
CREATE UNIQUE (g0_0)-[:BELONGS_TO]->(s0_0)
CREATE UNIQUE (s0_0)-[:HAS]->(g0_0)
CREATE UNIQUE (f0_0)-[:BELONGS_TO]->(s0_0)
CREATE UNIQUE (s0_0)-[:HAS]->(f0_0)
CREATE UNIQUE (ov0_0)-[:BELONGS_TO]->(s0_0)
CREATE UNIQUE (s0_0)-[:HAS]->(ov0_0)
CREATE UNIQUE (s0_0)-[:BELONGS_TO]->(o0)
CREATE UNIQUE (o0)-[:HAS]->(s0_0)
CREATE UNIQUE (u0)-[:IS]->(ro_ad)
CREATE UNIQUE (ro_ad)-[:HAS]->(u0)
CREATE UNIQUE (u0)-[:IS_USER_OF]->(o0)
CREATE UNIQUE (o0)-[:HAS_USER]->(u0)
CREATE UNIQUE (slg0)-[:BELONGS_TO]->(s0_0)
CREATE UNIQUE (s0_0)-[:HAS]->(slg0)
CREATE UNIQUE (n0_0)-[:BELONGS_TO]->(s0_0)
CREATE UNIQUE (s0_0)-[:HAS]->(n0_0)

// Add Schedule for ubersite
CREATE (sch0:Schedule {scheduleid: "uberschedule", name: "Default Schedule"})
CREATE (ce0:CalendarEvents {days: ["mon","tue","wed","thu","fri","sat","sun"], photocell_enabled: true, photocell_highLevel: 100, photocell_lowLevel: 0})
CREATE UNIQUE (ce0)-[:BELONGS_TO]->(sch0)
CREATE UNIQUE (sch0)-[:HAS]->(ce0)
CREATE (a0:Action {id: 2, time: "00:00:00", level: 100})
CREATE UNIQUE (ce0)-[:HAS]->(a0)
CREATE UNIQUE (a0)-[:BELONGS_TO]->(ce0)

CREATE UNIQUE (sch0)-[:BELONGS_TO]->(s0_0)
CREATE UNIQUE (s_00)-[:HAS]->(sch0)
CREATE UNIQUE (slg0)<-[:LINKED]-(sch0)
CREATE (nnw0:NoNetwork {photocell_enabled: true, photocell_highLevel: 100, photocell_lowLevel: 0})
CREATE UNIQUE (sch0)-[:HAS]->(nnw0)-[:BELONGS_TO]->(sch0)

;
