@startuml
    box  "NetSense Platform" #LightGrey
    participant NetSensePlatform
    end box

    box "TS Integration" #white
       participant TSAdapter
       participant TSAdapterCassandra
    end box

    box "ThingSpace" #LightGrey
       participant ThingSpaceKafka
       participant ThingSpaceService
    end box

    TSAdapter -> NetSensePlatform: Pull events
    TSAdapter -> TSAdapter: Uncompress message-pack messages

    alt Scenario: Creating a new device and pushing events
    TSAdapter -> ThingSpaceService: Create device in TS for the netsense device
    ThingSpaceService -> TSAdapter: New device created in TS
    TSAdapter -> TSAdapterCassandra: Insert the device id mapping(TS-Netsense)
    TSAdapter -> ThingSpaceKafka: Push events to kafka
    end

    alt Scenario: NetSense device already created in ThingSpace
    TSAdapter -> TSAdapterCassandra: Look up the mapping for the NetSense device id
    TSAdapterCassandra -> TSAdapter: device id mapping(TS-Netsense)
    TSAdapter -> TSAdapterCassandra: Insert the device mapping(TS-Netsense)
    TSAdapter -> ThingSpaceKafka: Push events to kafka
    end


@enduml