version: '2'
services:
  graphite:
    image: sitespeedio/graphite
    container_name: graphite
    ports:
      - 4001:80
  rabbitmq:
    image: rabbitmq:3.6.9-management
    container_name: rabbitmq
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=farallones
      - RABBITMQ_DEFAULT_PASS=sensity1
  legacy1:
    build: .
    image: sensity/legacy
    container_name: legacy1
    environment:
       - sname=true
       - clustered=true
       - legacy_service=legacy1
       - legacy_hosts=legacy1,legacy2,legacy3
       - rabbitmq_service=rabbitmq
       - graphite_service=graphite
    links:
      - rabbitmq
      - graphite
  legacy2:
    build: .
    image: sensity/legacy
    container_name: legacy2
    environment:
       - sname=true
       - clustered=true
       - legacy_service=legacy2
       - legacy_hosts=legacy1,legacy2,legacy3
       - rabbitmq_service=rabbitmq
       - graphite_service=graphite
    links:
      - rabbitmq
      - graphite
      - legacy1
  legacy3:
    build: .
    image: sensity/legacy
    container_name: legacy3
    environment:
       - sname=true
       - clustered=true
       - legacy_service=legacy3
       - legacy_hosts=legacy1,legacy2,legacy3
       - rabbitmq_service=rabbitmq
       - graphite_service=graphite
    links:
      - rabbitmq
      - graphite
      - legacy1
      - legacy2
  haproxy:
    image: haproxy:1.7
    container_name: haproxy
    ports:
      - 10443:10443
      - 8080:8080
    volumes:
      - ./priv/ssl/old/server-combined.pem:/var/priv/ssl/server-combined.pem
      - ./priv/ssl/old/sensity.crt:/var/priv/ssl/sensity.crt
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - legacy1
      - legacy2
      - legacy3
