%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.20.1 on {{2017,1,26},{13,35,33}}

-ifndef('DeviceMessages').
-define('DeviceMessages', true).

-define('DeviceMessages_gpb_version', "3.20.1").

-ifndef('DEVICEALARM_PB_H').
-define('DEVICEALARM_PB_H', true).
-record('DeviceAlarm',
        {alarmType,                     % = 1, {enum,'AlarmType'}
         alarmSeverity,                 % = 2, {enum,'AlarmSeverity'}
         msg                            % = 3, string (optional)
        }).
-endif.

-ifndef('LIGHTINGCLEARSCHEDULE_PB_H').
-define('LIGHTINGCLEARSCHEDULE_PB_H', true).
-record('LightingClearSchedule',
        {
        }).
-endif.

-ifndef('CALENDAREVENT_PB_H').
-define('CALENDAREVENT_PB_H', true).
-record('CalendarEvent',
        {sec,                           % = 1, uint32
         min,                           % = 2, uint32
         hr,                            % = 3, uint32
         wday,                          % = 4, uint32 (optional)
         mday,                          % = 5, uint32 (optional)
         mon,                           % = 6, uint32 (optional)
         year                           % = 7, uint32 (optional)
        }).
-endif.

-ifndef('LIGHTINGCTRL_PB_H').
-define('LIGHTINGCTRL_PB_H', true).
-record('LightingCtrl',
        {pri,                           % = 1, uint32
         mask,                          % = 2, uint32
         level,                         % = 3, bytes
         qualifiers                     % = 4, uint32 (optional)
        }).
-endif.

-ifndef('LIGHTINGSCHEDULEDEVENT_PB_H').
-define('LIGHTINGSCHEDULEDEVENT_PB_H', true).
-record('LightingScheduledEvent',
        {id,                            % = 1, uint32
         event,                         % = 2, {msg,'CalendarEvent'}
         state                          % = 3, {msg,'LightingCtrl'}
        }).
-endif.

-ifndef('DEVICEACTIONREQ_PB_H').
-define('DEVICEACTIONREQ_PB_H', true).
-record('DeviceActionReq',
        {actionType                     % = 1, {enum,'ActionType'}
        }).
-endif.

-ifndef('GPSACTIONREQ_PB_H').
-define('GPSACTIONREQ_PB_H', true).
-record('GpsActionReq',
        {actionType,                    % = 1, {enum,'GpsActionType'}
         iValue,                        % = 2, int32 (optional)
         sValue                         % = 3, string (optional)
        }).
-endif.

-ifndef('LIGHTINGSETAUTO_PB_H').
-define('LIGHTINGSETAUTO_PB_H', true).
-record('LightingSetAuto',
        {
        }).
-endif.

-ifndef('GPSSAMPLE_PB_H').
-define('GPSSAMPLE_PB_H', true).
-record('GpsSample',
        {gpsVer,                        % = 1, uint32 (optional)
         epochSecs,                     % = 2, fixed32 (optional)
         latAndLon,                     % = 3, fixed64 (optional)
         altAndMisc,                    % = 4, fixed32 (optional)
         snrAndMisc                     % = 5, fixed64 (optional)
        }).
-endif.

-ifndef('ASTRONOMICALEVENT_PB_H').
-define('ASTRONOMICALEVENT_PB_H', true).
-record('AstronomicalEvent',
        {body,                          % = 1, {enum,'AstronomicalBody'}
         atype,                         % = 2, {enum,'AstronomicalEventType'}
         zenith,                        % = 3, {enum,'AstronomicalEventZenith'}
         wday,                          % = 4, uint32 (optional)
         mday,                          % = 5, uint32 (optional)
         mon,                           % = 6, uint32 (optional)
         year                           % = 7, uint32 (optional)
        }).
-endif.

-ifndef('LIGHTINGFORCESTATE_PB_H').
-define('LIGHTINGFORCESTATE_PB_H', true).
-record('LightingForceState',
        {state,                         % = 1, {msg,'LightingCtrl'}
         ftype                          % = 2, {enum,'LightingForceType'} (optional)
        }).
-endif.

-ifndef('SENSORSAMPLE_PB_H').
-define('SENSORSAMPLE_PB_H', true).
-record('SensorSample',
        {sensor,                        % = 1, string
         time,                          % = 2, uint64
         value,                         % = 3, uint64
         units                          % = 4, string (optional)
        }).
-endif.

-ifndef('LIGHTINGASTRONOMICALEVENT_PB_H').
-define('LIGHTINGASTRONOMICALEVENT_PB_H', true).
-record('LightingAstronomicalEvent',
        {id,                            % = 1, uint32
         event,                         % = 2, {msg,'AstronomicalEvent'}
         state                          % = 3, {msg,'LightingCtrl'}
        }).
-endif.

-ifndef('SENSORSAMPLEREQ_PB_H').
-define('SENSORSAMPLEREQ_PB_H', true).
-record('SensorSampleReq',
        {sensor                         % = 1, string
        }).
-endif.

-ifndef('GPSACTIONRSP_PB_H').
-define('GPSACTIONRSP_PB_H', true).
-record('GpsActionRsp',
        {actionType,                    % = 1, {enum,'GpsActionType'}
         iValue,                        % = 2, int32 (optional)
         sValue                         % = 3, string (optional)
        }).
-endif.

-endif.
