%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.20.1 on {{2017,1,26},{13,35,33}}

-ifndef('Messages').
-define('Messages', true).

-define('Messages_gpb_version', "3.20.1").

-ifndef('DEVICEALARM_PB_H').
-define('DEVICEALARM_PB_H', true).
-record('DeviceAlarm',
        {alarmType,                     % = 1, {enum,'AlarmType'}
         alarmSeverity,                 % = 2, {enum,'AlarmSeverity'}
         msg                            % = 3, string (optional)
        }).
-endif.

-ifndef('LIGHTINGCLEARSCHEDULE_PB_H').
-define('LIGHTINGCLEARSCHEDULE_PB_H', true).
-record('LightingClearSchedule',
        {
        }).
-endif.

-ifndef('CALENDAREVENT_PB_H').
-define('CALENDAREVENT_PB_H', true).
-record('CalendarEvent',
        {sec,                           % = 1, uint32
         min,                           % = 2, uint32
         hr,                            % = 3, uint32
         wday,                          % = 4, uint32 (optional)
         mday,                          % = 5, uint32 (optional)
         mon,                           % = 6, uint32 (optional)
         year                           % = 7, uint32 (optional)
        }).
-endif.

-ifndef('LIGHTINGCTRL_PB_H').
-define('LIGHTINGCTRL_PB_H', true).
-record('LightingCtrl',
        {pri,                           % = 1, uint32
         mask,                          % = 2, uint32
         level,                         % = 3, bytes
         qualifiers                     % = 4, uint32 (optional)
        }).
-endif.

-ifndef('LIGHTINGSCHEDULEDEVENT_PB_H').
-define('LIGHTINGSCHEDULEDEVENT_PB_H', true).
-record('LightingScheduledEvent',
        {id,                            % = 1, uint32
         event,                         % = 2, {msg,'CalendarEvent'}
         state                          % = 3, {msg,'LightingCtrl'}
        }).
-endif.

-ifndef('X509UPDATEREQ_PB_H').
-define('X509UPDATEREQ_PB_H', true).
-record('X509UpdateReq',
        {x509UpdateURL,                 % = 1, string
         x509Update,                    % = 2, {enum,'X509Update'}
         httpsPort                      % = 3, uint32 (optional)
        }).
-endif.

-ifndef('LOGINREQ_PB_H').
-define('LOGINREQ_PB_H', true).
-record('LoginReq',
        {nodeId,                        % = 1, string
         protocolVersion,               % = 2, uint64
         clientType,                    % = 3, string (optional)
         swVerId,                       % = 4, string (optional)
         netName,                       % = 5, string (optional)
         profileName,                   % = 6, string (optional)
         assocChannel,                  % = 7, string (optional)
         configToken,                   % = 8, string (optional)
         localIP,                       % = 9, string (optional)
         time,                          % = 10, uint64 (optional)
         bssid,                         % = 11, string (optional)
         mac,                           % = 12, string (optional)
         auth                           % = 13, {enum,'WiFiAuthType'} (optional)
        }).
-endif.

-ifndef('VIDEOUPLOADREQ_PB_H').
-define('VIDEOUPLOADREQ_PB_H', true).
-record('VideoUploadReq',
        {sensorId,                      % = 1, string
         startTime,                     % = 2, uint64 (optional)
         endTime,                       % = 3, uint64 (optional)
         fileType                       % = 4, string (optional)
        }).
-endif.

-ifndef('LOGINRESP_PB_H').
-define('LOGINRESP_PB_H', true).
-record('LoginResp',
        {okay,                          % = 1, bool
         time                           % = 2, uint64 (optional)
        }).
-endif.

-ifndef('ERRORRESP_PB_H').
-define('ERRORRESP_PB_H', true).
-record('ErrorResp',
        {message                        % = 1, string
        }).
-endif.

-ifndef('ASTRONOMICALEVENT_PB_H').
-define('ASTRONOMICALEVENT_PB_H', true).
-record('AstronomicalEvent',
        {body,                          % = 1, {enum,'AstronomicalBody'}
         atype,                         % = 2, {enum,'AstronomicalEventType'}
         zenith,                        % = 3, {enum,'AstronomicalEventZenith'}
         wday,                          % = 4, uint32 (optional)
         mday,                          % = 5, uint32 (optional)
         mon,                           % = 6, uint32 (optional)
         year                           % = 7, uint32 (optional)
        }).
-endif.

-ifndef('LIGHTINGASTRONOMICALEVENT_PB_H').
-define('LIGHTINGASTRONOMICALEVENT_PB_H', true).
-record('LightingAstronomicalEvent',
        {id,                            % = 1, uint32
         event,                         % = 2, {msg,'AstronomicalEvent'}
         state                          % = 3, {msg,'LightingCtrl'}
        }).
-endif.

-ifndef('LIGHTINGSETAUTO_PB_H').
-define('LIGHTINGSETAUTO_PB_H', true).
-record('LightingSetAuto',
        {
        }).
-endif.

-ifndef('LIGHTINGFORCESTATE_PB_H').
-define('LIGHTINGFORCESTATE_PB_H', true).
-record('LightingForceState',
        {state,                         % = 1, {msg,'LightingCtrl'}
         ftype                          % = 2, {enum,'LightingForceType'} (optional)
        }).
-endif.

-ifndef('GPSACTIONRSP_PB_H').
-define('GPSACTIONRSP_PB_H', true).
-record('GpsActionRsp',
        {actionType,                    % = 1, {enum,'GpsActionType'}
         iValue,                        % = 2, int32 (optional)
         sValue                         % = 3, string (optional)
        }).
-endif.

-ifndef('GPSACTIONREQ_PB_H').
-define('GPSACTIONREQ_PB_H', true).
-record('GpsActionReq',
        {actionType,                    % = 1, {enum,'GpsActionType'}
         iValue,                        % = 2, int32 (optional)
         sValue                         % = 3, string (optional)
        }).
-endif.

-ifndef('GPSSAMPLE_PB_H').
-define('GPSSAMPLE_PB_H', true).
-record('GpsSample',
        {gpsVer,                        % = 1, uint32 (optional)
         epochSecs,                     % = 2, fixed32 (optional)
         latAndLon,                     % = 3, fixed64 (optional)
         altAndMisc,                    % = 4, fixed32 (optional)
         snrAndMisc                     % = 5, fixed64 (optional)
        }).
-endif.

-ifndef('SENSORSAMPLEREQ_PB_H').
-define('SENSORSAMPLEREQ_PB_H', true).
-record('SensorSampleReq',
        {sensor                         % = 1, string
        }).
-endif.

-ifndef('TIMERESP_PB_H').
-define('TIMERESP_PB_H', true).
-record('TimeResp',
        {time                           % = 1, uint64
        }).
-endif.

-ifndef('TIMEREQ_PB_H').
-define('TIMEREQ_PB_H', true).
-record('TimeReq',
        {
        }).
-endif.

-ifndef('VIDEOUPLOADRESP_PB_H').
-define('VIDEOUPLOADRESP_PB_H', true).
-record('VideoUploadResp',
        {sensorId,                      % = 1, string
         url                            % = 2, string
        }).
-endif.

-ifndef('SENSORSAMPLE_PB_H').
-define('SENSORSAMPLE_PB_H', true).
-record('SensorSample',
        {sensor,                        % = 1, string
         time,                          % = 2, uint64
         value,                         % = 3, uint64
         units                          % = 4, string (optional)
        }).
-endif.

-ifndef('DEVICEACTIONREQ_PB_H').
-define('DEVICEACTIONREQ_PB_H', true).
-record('DeviceActionReq',
        {actionType                     % = 1, {enum,'ActionType'}
        }).
-endif.

-ifndef('SOFTWAREUPDATEREQ_PB_H').
-define('SOFTWAREUPDATEREQ_PB_H', true).
-record('SoftwareUpdateReq',
        {swUpdateURL                    % = 1, string
        }).
-endif.

-ifndef('CONFIGRESPDONE_PB_H').
-define('CONFIGRESPDONE_PB_H', true).
-record('ConfigRespDone',
        {
        }).
-endif.

-ifndef('KVPAIR_PB_H').
-define('KVPAIR_PB_H', true).
-record('KVPair',
        {key,                           % = 1, string
         sValue,                        % = 2, string (optional)
         lValue,                        % = 3, int64 (optional)
         bValue                         % = 4, bool (optional)
        }).
-endif.

-ifndef('CONFIGRESP_PB_H').
-define('CONFIGRESP_PB_H', true).
-record('ConfigResp',
        {pair                           % = 1, {msg,'KVPair'}
        }).
-endif.

-ifndef('UNUSEDCONFIGREQ_PB_H').
-define('UNUSEDCONFIGREQ_PB_H', true).
-record('UnusedConfigReq',
        {
        }).
-endif.

-ifndef('ENVELOPE_PB_H').
-define('ENVELOPE_PB_H', true).
-record('Envelope',
        {loginReq,                      % = 1, {msg,'LoginReq'} (optional)
         loginResp,                     % = 2, {msg,'LoginResp'} (optional)
         unusedConfigReq,               % = 3, {msg,'UnusedConfigReq'} (optional)
         configResp,                    % = 4, {msg,'ConfigResp'} (optional)
         configRespDone,                % = 5, {msg,'ConfigRespDone'} (optional)
         softwareUpdateReq,             % = 6, {msg,'SoftwareUpdateReq'} (optional)
         deviceAlarm,                   % = 7, {msg,'DeviceAlarm'} (optional)
         deviceAction,                  % = 8, {msg,'DeviceActionReq'} (optional)
         x509Update,                    % = 9, {msg,'X509UpdateReq'} (optional)
         sensorSample,                  % = 10, {msg,'SensorSample'} (optional)
         videoUploadReq,                % = 11, {msg,'VideoUploadReq'} (optional)
         videoUploadResp,               % = 12, {msg,'VideoUploadResp'} (optional)
         timeReq,                       % = 13, {msg,'TimeReq'} (optional)
         timeResp,                      % = 14, {msg,'TimeResp'} (optional)
         sensorSampleReq,               % = 15, {msg,'SensorSampleReq'} (optional)
         gpsSample,                     % = 16, {msg,'GpsSample'} (optional)
         gpsActionReq,                  % = 17, {msg,'GpsActionReq'} (optional)
         gpsActionRsp,                  % = 18, {msg,'GpsActionRsp'} (optional)
         lightingForceState,            % = 20, {msg,'LightingForceState'} (optional)
         lightingSetAuto,               % = 21, {msg,'LightingSetAuto'} (optional)
         lightingScheduledEvent,        % = 22, {msg,'LightingScheduledEvent'} (optional)
         lightingAstronomicalEvent,     % = 23, {msg,'LightingAstronomicalEvent'} (optional)
         lightingClearSchedule          % = 24, {msg,'LightingClearSchedule'} (optional)
        }).
-endif.

-endif.
