%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.20.1 on {{2016,6,13},{9,57,14}}

-ifndef(example).
-define(example, true).

-define(example_gpb_version, "3.20.1").

-ifndef('SHORT_PB_H').
-define('SHORT_PB_H', true).
-record('Short',
        {name,                          % = 1, string
         email                          % = 2, string (optional)
        }).
-endif.

-endif.
