%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.20.1 on {{2016,3,30},{10,23,27}}

-ifndef(message).
-define(message, true).

-define(message_gpb_version, "3.20.1").

-ifndef('LOCATION_PB_H').
-define('LOCATION_PB_H', true).
-record(location,
        {region,                        % = 1, string
         country                        % = 2, string
        }).
-endif.

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record(person,
        {name,                          % = 1, string
         address,                       % = 2, string
         phone_number,                  % = 3, string
         age,                           % = 4, int32
         location                       % = 5, {msg,location} (optional)
        }).
-endif.

-endif.
