%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.20.1 on {{2016,3,30},{10,23,27}}

-ifndef(meta_proto).
-define(meta_proto, true).

-define(meta_proto_gpb_version, "3.20.1").

-ifndef('META_PB_H').
-define('META_PB_H', true).
-record(meta,
        {type,                          % = 1, {enum,'meta.msgtype'}
         msg                            % = 2, bytes
        }).
-endif.

-endif.
