package com.verizon.netsense.utils

import java.util.zip.CRC32

import akka.http.scaladsl.model._
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.Route
import com.verizon.netsense.utils
import org.json4s.DefaultFormats
import org.json4s.native.Serialization.write

/**
 * Created by Davor on 5/12/17.
 */
object ConfigUtils {

  implicit val formats = DefaultFormats

  val vdkDefaultConfig = """{
    "name":"VDKMASTER default configuration",
    "al.left.setbrightness": 50,
    "al.left.setmode": "M",
    "al.right.setbrightness": 50,
    "al.right.setmode": "M",
    "alarm.redis.memory_threshold": 0.9,
    "application_server": "webrtc.sensity.com",
    "application_server_port": 8443,
    "appos.timezone": "America/New_York",
    "glassl.display.aspect_ratio": "full-screen",
    "glassl.display.blue.gain": 256,
    "glassl.display.blue.offset": -20,
    "glassl.display.brightness": 70,
    "glassl.display.brightness.normal": 100,
    "glassl.display.brightness.warm": 75,
    "glassl.display.brightness.warmer": 50,
    "glassl.display.color-temp": 0,
    "glassl.display.contrast": 260,
    "glassl.display.film_display_mode": "normal-3:2",
    "glassl.display.film_mode_detection": "off",
    "glassl.display.green.gain": 256,
    "glassl.display.green.offset": -20,
    "glassl.display.hue": 0,
    "glassl.display.main_source_input": "dvi",
    "glassl.display.mode.ccs": "video",
    "glassl.display.mode.dynamic-nr": "high",
    "glassl.display.mode.main-dcdi": "off",
    "glassl.display.mode.main-madi": "adaptive",
    "glassl.display.mode.mpeg-nr": "on",
    "glassl.display.mode.selection-1080p": "graphics",
    "glassl.display.mode.selection-720p": "graphics",
    "glassl.display.mpeg-nr": 30,
    "glassl.display.pip_mode": "off",
    "glassl.display.power": "on",
    "glassl.display.power_off_type": "full",
    "glassl.display.red.gain": 256,
    "glassl.display.red.offset": -20,
    "glassl.display.saturation": 256,
    "glassl.display.sharpness": 10,
    "glassl.display.speed_mode": "on",
    "glassl.display.temp.max": 67,
    "glassl.display.temp.min": 0,
    "glassl.display.temp.warm": 55,
    "glassl.display.temp.warmer": 60,
    "glassr.display.aspect_ratio": "full-screen",
    "glassr.display.blue.gain": 256,
    "glassr.display.blue.offset": -20,
    "glassr.display.brightness": 70,
    "glassr.display.brightness.normal": 100,
    "glassr.display.brightness.warm": 75,
    "glassr.display.brightness.warmer": 50,
    "glassr.display.color-temp": 0,
    "glassr.display.contrast": 260,
    "glassr.display.film_display_mode": "normal-3:2",
    "glassr.display.film_mode_detection": "off",
    "glassr.display.green.gain": 256,
    "glassr.display.green.offset": -20,
    "glassr.display.hue": 0,
    "glassr.display.main_source_input": "dvi",
    "glassr.display.mode.ccs": "video",
    "glassr.display.mode.dynamic-nr": "high",
    "glassr.display.mode.main-dcdi": "off",
    "glassr.display.mode.main-madi": "adaptive",
    "glassr.display.mode.mpeg-nr": "on",
    "glassr.display.mode.selection-1080p": "graphics",
    "glassr.display.mode.selection-720p": "graphics",
    "glassr.display.mpeg-nr": 30,
    "glassr.display.pip_mode": "off",
    "glassr.display.power_off_type": "full",
    "glassr.display.power": "high",
    "glassr.display.red.gain": 256,
    "glassr.display.red.offset": -20,
    "glassr.display.saturation": 256,
    "glassr.display.sharpness": 10,
    "glassr.display.speed_mode": "on",
    "glassr.display.temp.max": 67,
    "glassr.display.temp.min": 0,
    "glassr.display.temp.warm": 55,
    "glassr.display.temp.warmer": 60,
    "lr.setcolor": "ffffff",
    "network.eth-x.ip": "172.17.100.1",
    "network.eth-x.method": "auto",
    "network.eth-x.netmask": 24,
    "network.firewall.protocols": "",
    "network.firewall.ports": "",
    "network.server.vpn": "medianodevpn.sensity.com",
    "network.vpn_on_demand": false,
    "pebble.display.aspect_ratio": "full-screen",
    "pebble.display.blue.gain": 256,
    "pebble.display.blue.offset": -20,
    "pebble.display.brightness": 60,
    "pebble.display.brightness.normal": 100,
    "pebble.display.brightness.warm": 75,
    "pebble.display.brightness.warmer": 50,
    "pebble.display.color-temp": 0,
    "pebble.display.contrast": 180,
    "pebble.display.film_display_mode": "normal-3:2",
    "pebble.display.film_mode_detection": "off",
    "pebble.display.main_source_input": "dvi",
    "pebble.display.green.gain": 256,
    "pebble.display.green.offset": -20,
    "pebble.display.hue": 0, 
    "pebble.display.mode.ccs": "video",
    "pebble.display.mode.dynamic-nr": "high",
    "pebble.display.mode.main-dcdi": "off",
    "pebble.display.mode.main-madi": "adaptive",
    "pebble.display.mode.mpeg-nr": "on",
    "pebble.display.mode.selection-1080p": "graphics",
    "pebble.display.mode.selection-720p": "graphics",
    "pebble.display.mpeg-nr": 30,
    "pebble.display.power": "high",
    "pebble.display.power_off_type": "full",
    "pebble.display.pip_mode": "off",
    "pebble.display.red.gain": 256,
    "pebble.display.red.offset": -20,
    "pebble.display.saturation": 256,
    "pebble.display.sharpness": 10,
    "pebble.display.speed_mode": "on",
    "pebble.display.temp.max": 67,
    "pebble.display.temp.min": 0,
    "pebble.display.temp.warm": 55,
    "pebble.display.temp.warmer": 60,
    "siteid":"defaultVDK"
  }"""

  val falconDefaultConfig = """{
    "name":"Falcon default configuration",
    "camera.0.autoexposure": true,
    "camera.0.autogain": true,
    "camera.0.colortemp": 6500,
    "camera.0.exposure": 15,
    "camera.0.flickermode": "60Hz",
    "camera.0.gain": 15,
    "camera.0.indoormode": false,
    "camera.0.scanmode": "none",
    "camera.0.master": 0,
    "camera.0.wdrmode": true,
    "camera.1.autoexposure": true,
    "camera.1.autogain": true,
    "camera.1.colortemp": 6500,
    "camera.1.exposure": 15,
    "camera.1.flickermode": "60Hz",
    "camera.1.gain": 15,
    "camera.1.indoormode": false,
    "camera.1.scanmode": "none",
    "camera.1.wdrmode": true,
    "rtsp.service": 554,
    "Genetec.custom_events": "enter,left",
    "camera.0.enabled": true,
    "camera.0.streamH.bitrate": 2500000,
    "camera.0.streamH.format": "720p",
    "camera.0.streamH.framerate": 15,
    "camera.0.streamH.gopsize": 30,
    "camera.0.streamH.storage.diskquota": 0.25,
    "camera.0.streamH.storage.recordevents": "Car Entering",
    "camera.0.streamH.storage.recordmode": 0,
    "camera.0.streamH.storage.recordpostamble": 30,
    "camera.0.streamH.storage.recordpreamble": 30,
    "camera.0.streamH.storage.vaqa.0.duration": "3m",
    "camera.0.streamH.storage.vaqa.0.interval": "1h",
    "camera.0.streamH.storage.vaqa.0.qty": 24,
    "camera.0.streamH.storage.vaqa.1.duration": "3m",
    "camera.0.streamH.storage.vaqa.1.interval": "25h",
    "camera.0.streamH.storage.vaqa.1.qty": 0,
    "camera.0.streamL.bitrate": 500000,
    "camera.0.streamL.format": "360p",
    "camera.0.streamL.framerate": 5,
    "camera.0.streamL.gopsize": 5,
    "camera.0.streamL.storage.diskquota": 0.25,
    "camera.0.streamL.storage.recordevents": "Car Entering",
    "camera.0.streamL.storage.recordmode": 1,
    "camera.0.streamL.storage.recordpostamble": 30,
    "camera.0.streamL.storage.recordpreamble": 30,
    "camera.1.enabled": true,
    "camera.1.streamH.bitrate": 2500000,
    "camera.1.streamH.format": "720p",
    "camera.1.streamH.framerate": 15,
    "camera.1.streamH.gopsize": 30,
    "camera.1.streamH.storage.diskquota": 0.25,
    "camera.1.streamH.storage.recordevents": "Car Entering",
    "camera.1.streamH.storage.recordmode": 0,
    "camera.1.streamH.storage.recordpostamble": 30,
    "camera.1.streamH.storage.recordpreamble": 30,
    "camera.1.streamH.storage.vaqa.0.duration": "3m",
    "camera.1.streamH.storage.vaqa.0.interval": "1h",
    "camera.1.streamH.storage.vaqa.0.qty": 24,
    "camera.1.streamH.storage.vaqa.1.duration": "3m",
    "camera.1.streamH.storage.vaqa.1.interval": "25h",
    "camera.1.streamH.storage.vaqa.1.qty": 0,
    "camera.1.streamL.bitrate": 500000,
    "camera.1.streamL.format": "360p",
    "camera.1.streamL.framerate": 5,
    "camera.1.streamL.gopsize": 5,
    "camera.1.streamL.storage.diskquota": 0.25,
    "camera.1.streamL.storage.recordevents": "Car Entering",
    "camera.1.streamL.storage.recordmode": 1,
    "camera.1.streamL.storage.recordpostamble": 30,
    "camera.1.streamL.storage.recordpreamble": 30,
    "evtgrab.capint": 3600,
    "evtgrab.dint": 600,
    "evtgrab.nfiles": 1000,
    "evtgrab.periodic_only": false,
    "mediaserver.nomve": false,
    "mediaserver.video_codec": "h264",
    "mediaserver.wmm_qos": true,
    "storage.maxsessions": 15,
    "storageserver.cache_size": 10000000000,
    "storageserver.max_clip_size": 200000000,
    "alarm.redis.memory_threshold": 0.9,
    "application_server": "webrtc.sensity.com",
    "application_server_port": 8443,
    "network.eth-x.ip": "172.17.100.1",
    "network.eth-x.method": "auto",
    "network.eth-x.netmask": 24,
    "network.eth-x.leasetime": "24h",
    "network.firewall.protocols": "",
    "network.firewall.ports": "",
    "network.server.vpn": "medianodevpn.sensity.com",
    "network.vpn_on_demand": false,
    "network.wlan-x.security": "wpa2p",
    "network.wlan-x.security.bgscan-long-interval": 360,
    "network.wlan-x.security.bgscan-short-interval": 60,
    "network.wlan-x.security.bgscan-signal-threshold": -60,
    "network.wlan-x.security.psk": "netsense",
    "network.wlan-x.ssid": "SensityDefault",
    "network.wlan-y.security": "wpa2p",
    "network.wlan-y.security.bgscan-long-interval": 360,
    "network.wlan-y.security.bgscan-short-interval": 60,
    "network.wlan-y.security.bgscan-signal-threshold": -60,
    "network.wlan-y.security.psk": "kentspeed",
    "network.wlan-y.ssid": "XeraL2"
  }"""
  val cnextDefaultConfig = """{
    "name":"NGCN default configuration",
    "alarm.redis.memory_threshold": 0.9,
    "application_server": "webrtc.sensity.com",
    "application_server_port": 8443,
    "lctrl.dimmer.vmax": 10000,
    "lctrl.ltype": 1,
    "lctrl.lvlrate.fast": 1310740000,
    "lctrl.lvlrate.light": 65536200,
    "lctrl.lvlrate.motion": 262144500,
    "lctrl.lvlrate.norm": 131074000,
    "lctrl.trigger.nonett": 900,
    "lctrl.trigger.off.dint": 300000,
    "lctrl.trigger.offt": 100000,
    "lctrl.trigger.on.dint": 5000,
    "lctrl.trigger.ont": 5000,
    "network.eth-x.ip": "172.17.100.1",
    "network.eth-x.leasetime": "24h",
    "network.eth-x.method": "auto",
    "network.eth-x.netmask": 24,
    "network.firewall.ports": "",
    "network.firewall.protocols": "",
    "network.ppp-x.apn": "VZWINTERNET",
    "network.server.vpn": "medianodevpn.sensity.com",
    "network.vpn_on_demand": false,
    "network.wlan-x.security": "wpa2p",
    "network.wlan-x.security.bgscan-long-interval": 360,
    "network.wlan-x.security.bgscan-short-interval": 60,
    "network.wlan-x.security.bgscan-signal-threshold": -60,
    "network.wlan-x.security.psk": "netsense",
    "network.wlan-x.ssid": "SensityDefault",
    "network.wlan-y.security": "wpa2p",
    "network.wlan-y.security.bgscan-long-interval": 360,
    "network.wlan-y.security.bgscan-short-interval": 60,
    "network.wlan-y.security.bgscan-signal-threshold": -60,
    "network.wlan-y.security.psk": "kentspeed",
    "network.wlan-y.ssid": "XeraL2",
    "podbus.disable": false,
    "poe.enabled": false,
    "pwr.noload.i": 15,
    "pwr.noload.mode": 1
  }"""

  val merlinDefaultConfig = """{
    "name":"Merlin default configuration",
    "Genetec.custom_events": "enter,left",
    "camera.0.autoexposure": true,
    "camera.0.autogain": true,
    "camera.0.binning": false,
    "camera.0.enabled": true,
    "camera.0.exposure": 33333,
    "camera.0.flickermode": "60Hz",
    "camera.0.gain": 1.0,
    "camera.0.master": 0,
    "rtsp.service": 554,
    "camera.0.scanmode": "none",
    "camera.0.streamH.format": "1080p",
    "camera.0.streamH.bitrate": 6000000,
    "camera.0.streamH.framerate": 30,
    "camera.0.streamH.gopsize": 30,
    "camera.0.streamH.storage.diskquota": 0.5,
    "camera.0.streamH.storage.recordevents": "Car Entering",
    "camera.0.streamH.storage.recordmode": 0,
    "camera.0.streamH.storage.recordpostamble": 30,
    "camera.0.streamH.storage.recordpreamble": 30,
    "camera.0.streamH.storage.vaqa.0.duration": "3m",
    "camera.0.streamH.storage.vaqa.0.interval": "1h",
    "camera.0.streamH.storage.vaqa.0.qty": 24,
    "camera.0.streamH.storage.vaqa.1.duration": "3m",
    "camera.0.streamH.storage.vaqa.1.interval": "25h",
    "camera.0.streamH.storage.vaqa.1.qty": 0,
    "camera.0.streamL.bitrate": 2500000,
    "camera.0.streamL.format": "720p",
    "camera.0.streamL.framerate": 10,
    "camera.0.streamL.gopsize": 5,
    "camera.0.streamL.storage.diskquota": 0.5,
    "camera.0.streamL.storage.recordevents": "Car Entering",
    "camera.0.streamL.storage.recordmode": 1,
    "camera.0.streamL.storage.recordpostamble": 30,
    "camera.0.streamL.storage.recordpreamble": 30,
    "camera.1.autoexposure": true,
    "camera.1.autogain": true,
    "camera.1.enabled": true,
    "camera.1.exposure": 15,
    "camera.1.flickermode": "60Hz",
    "camera.1.gain": 15,
    "camera.1.scanmode": "none",
    "camera.1.streamH.bitrate": 6000000,
    "camera.1.streamH.format": "1080p",
    "camera.1.streamH.framerate": 30,
    "camera.1.streamH.gopsize": 30,
    "camera.1.streamH.storage.recordevents": "Car Entering",
    "camera.1.streamH.storage.recordpostamble": 30,
    "camera.1.streamH.storage.recordpreamble": 30,
    "camera.1.streamH.storage.vaqa.0.duration": "3m",
    "camera.1.streamH.storage.vaqa.0.interval": "1h",
    "camera.1.streamH.storage.vaqa.0.qty": 24,
    "camera.1.streamH.storage.vaqa.1.duration": "3m",
    "camera.1.streamH.storage.vaqa.1.interval": "25h",
    "camera.1.streamH.storage.vaqa.1.qty": 0,
    "camera.1.streamL.bitrate": 2500000,
    "camera.1.streamL.format": "720p",
    "camera.1.streamL.framerate": 10,
    "camera.1.streamL.gopsize": 5,
    "camera.1.streamL.storage.recordevents": "Car Entering",
    "camera.1.streamL.storage.recordpostamble": 30,
    "camera.1.streamL.storage.recordpreamble": 30,
    "evtgrab.capint": 3600,
    "evtgrab.dint": 600,
    "evtgrab.nfiles": 1000,
    "evtgrab.periodic_only": false,
    "mediaserver.nomve": false,
    "mediaserver.rtspsrc": "",
    "mediaserver.video_codec": "h264",
    "mediaserver.wmm_qos": true,
    "storage.maxsessions": 15,
    "storageserver.cache_size": 10000000000,
    "storageserver.max_clip_size": 200000000,
    "alarm.redis.memory_threshold": 0.9,
    "application_server": "webrtc.sensity.com",
    "application_server_port": 8443,
    "network.eth-x.ip": "",
    "network.eth-x.method": "auto",
    "network.eth-x.netmask": 24,
    "network.firewall.protocols": "",
    "network.firewall.ports": "",
    "network.server.vpn": "medianodevpn.sensity.com",
    "network.vpn_on_demand": false
  }"""

  val defaultConfigMap: Map[DeviceModels.Model, (String, String)] =
    Map(DeviceModels.FALCON   -> ("7bad8e7d-5ab1-4516-913c-fff857854c7f", falconDefaultConfig),
        DeviceModels.MERLIN   -> ("90845063-26ae-4fa8-8e73-22b605d55fea", merlinDefaultConfig),
        DeviceModels.UNODEV7  -> ("f8c92f4e-24d3-4298-92f5-a32d23162c01", falconDefaultConfig),
        DeviceModels.VDK      -> ("16c92f4e-24d3-4298-92f5-a32d23162c01", vdkDefaultConfig),
        DeviceModels.CNEXT    -> ("7bad8e7d-4fa8-26ae-92f5-22b605d55fea", cnextDefaultConfig))

  def getToken(config: Map[String, Any]): String = {
    val digest = write(config.toSeq.sortBy(_._1))
    val crc    = new CRC32
    val bytes  = digest.getBytes
    crc.update(bytes, 0, bytes.length)
    crc.getValue.toString
  }
}

object HttpServices {
  val route: Route =
    get {
      path("status") {
        complete(HttpEntity(ContentTypes.`application/json`, "ok"))
      }
    }
}
