@startuml
    participant Kafka
    participant Gps_Service
    participant In_Memory_Cassandra
    participant Cassandra
    box #LightGrey
        participant Kafka
    end box
    box  #LightBlue
       participant Gps_Service
       participant Cassandra
       participant In_Memory_Cassandra
    end box

    hnote over Kafka : Topic: core.gps topic
    Kafka <- Gps_Service: subscribes to the core.gps topic
    Gps_Service -> Gps_Service: on new message
    Gps_Service -> In_Memory_Cassandra: Look up org hierarchy based on the node_id
    In_Memory_Cassandra -> Gps_Service: org hierarchy
    Gps_Service -> Gps_Service: validate and enrich the message()
    Gps_Service -> Cassandra: Insert or update the enriched message(i,e Gps)

@enduml