@startuml
    participant Client_Application
    participant Interface_Service
    participant Kafka
    participant Gps_Service
    participant ACL_Service
    participant Cassandra
    participant DataDealer
    participant ZMQ
    box  #LightGreen
       participant Client_Application
       participant Interface_Service
       participant ACL_Service
    end box
    box #LightGrey
        participant Kafka
        participant ZMQ
    end box
    box  #LightBlue
       participant Gps_Service
       participant DataDealer
       participant Cassandra
    end box

    Client_Application -> Interface_Service: API call
    hnote over Kafka : Topic: ACL REQUEST Topic
    Interface_Service -> Kafka: authentication request
    Kafka -> ACL_Service: authentication request
    ACL_Service -> ACL_Service: look up the org hierarchy & validate
    ACL_Service -> Kafka: authentication response
    hnote over Kafka : Topic: Interface Service RESPONSE Topic
    Interface_Service  -> Kafka: subscribe to Authentication RESPONSE topic
    Interface_Service -> ZMQ: Get node(s) request
    DataDealer -> ZMQ: Consume request
    DataDealer -> DataDealer: load node(s) from neo4j
    DataDealer -> ZMQ: response with node(s)
    Interface_Service -> ZMQ  : Consume response node(s)



    hnote over Kafka : Topic: GPS Service REQUEST topic
    Interface_Service  -> Kafka: Get gps of node(s)
    Kafka <- Gps_Service: subscribes to the REQUEST topic
    Gps_Service -> Gps_Service: on new message, validate the request
    Gps_Service -> Gps_Service: business logic based on the request type
    Gps_Service -> Cassandra: read/write/update/delete gps(s)
    Cassandra -> Gps_Service: result
    Gps_Service -> Kafka: publish result to reponse topic
    hnote over Kafka : Topic: RESPONSE
    Kafka <- Interface_Service: subscribes result from reponse topic
    Interface_Service -> Client_Application: response
@enduml