@startuml
    box  "Client" #LightGrey
    participant REST_API
    end box

    box "Interface Service" #white
       participant MQTT_Client
       participant  Embedded_MQTT_Broker
       participant  NotificationManager
       participant NotificationMessenger
    end box

    box "Alert Service" #LightGrey
       participant AlertMicroService
    end box

    box "SSE Micro Service" #LightGrey
       participant SSEMicroService
    end box

    alt Scenario: SSE Stream for Alerts to "Embedded MQTT Broker"
        SSEMicroService -> Embedded_MQTT_Broker: All alerts
    end

    alt Scenario: Subscibe events
       MQTT_Client -> Embedded_MQTT_Broker: "/streamv1/+/+/+/DeviceAlarm"
       Embedded_MQTT_Broker -> MQTT_Client: Alert Stream
    end

    alt Scenario: Handle Each Alert
       MQTT_Client -> NotificationManager: Alert
       NotificationManager -> AlertMicroService: Get All NotificationsByName
       AlertMicroService -> NotificationManager: Notifications
       NotificationManager -> NotificationManager: Check alert against holdoff rules
       NotificationManager -> AlertMicroService: Get NotificationSys
       AlertMicroService -> NotificationManager: Notification

       NotificationManager -> AlertMicroService: Get AlertSys (Using Alert Topic)
       AlertMicroService -> NotificationManager: Alert

       NotificationManager -> NotificationManager: Check User Type and display flags in Alert
       NotificationManager -> NotificationMessenger: Send SMS/Email
       NotificationMessenger -> NotificationMessenger: Send SMS/Email. SMS - Amazon SNS, Email - Amazon SES.
    end


@enduml