@startuml
    box  "Client" #LightGrey
    participant REST_API
    end box

    box "Interface Service" #white
       participant AlarmController
    end box

    box "Kafka" #white
           participant api.reply.interface
           participant ms.request.acl
           participant ms.request.alert
    end box

    box "Alert Service" #LightGrey
       participant AlertMicroService
    end box

    alt Scenario: Get All UF Alarms
        AlarmController -> ms.request.acl
        ms.request.acl -> ms.request.acl
        ms.request.acl -> api.reply.interface
        api.reply.interface -> AlarmController

        AlarmController -> ms.request.alert
        ms.request.alert -> AlertMicroService
        AlertMicroService -> AlertMicroService
        AlertMicroService -> api.reply.interface
        api.reply.interface -> AlarmController: UF Alarms
        AlarmController -> REST_API: UF Alarms
    end

    alt Scenario: Add/Update/Reset/Delete/Get UF Alarm ById
        REST_API -> AlarmController: UF Alarm CRUD (Add/Update/Reset/Delete/GetUF_AlarmById)
        AlarmController -> ms.request.acl
        ms.request.acl -> ms.request.acl
        ms.request.acl -> api.reply.interface
        api.reply.interface -> AlarmController
        
        AlarmController -> ms.request.alert
        ms.request.alert -> AlertMicroService
        AlertMicroService -> AlertMicroService
        AlertMicroService -> api.reply.interface
        api.reply.interface -> AlarmController: UF Alarm
        AlarmController -> REST_API: UF Alarm
    end

@enduml